### ISSUE TITLE
[BUG] Toolbar doesn't adhere to dark mode

### ISSUE THREAD

**Issue by debkanchan** [Darginec05/Yoopta-Editor#260]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

In dark mode, toolbar background is still white while background is dark

### Steps to Reproduce

- init a next.js project
- setup a theme switcher using next/themes
- setup shadcn/ui
- copy any [block](https://ui.shadcn.com/blocks)
- add a yoopta editor anywhere with toolbar plugin
- add text
- switch to dark mode
- select text

### Environment

- OS: MacOS Sonoma 14.5 (23F79)
- Browser: Arc Version 1.54.0 (52220) [Chromium Engine Version 127.0.6533.89]

### Screenshots

<img width="583" alt="Screenshot 2024-08-20 at 12 22 55 PM" src="https://github.com/user-attachments/assets/0e3ec4fe-71b5-4f0a-bffd-fcdfdb88bb07">

### Do you want to work on this issue?

No

**Comment by iamhenry** [comment]
im running into the same issues with a very similar stack

**Comment by trancethehuman** [comment]
Same here. Next.js

**Comment by trancethehuman** [comment]
If you create your own toolbar, with custom action menu styling, you can resolve it (but then you won't get to use the default toolbar)

Here's the example from the docs for setting up a toolbar that's similar to Notion's: https://github.dev/Darginec05/Yoopta-Editor/blob/master/web/next-example/src/components/examples/withCustomToolbar/index.tsx

And in FloatingPortal's div that wraps ActionMenu, you can style that (I use tailwind so I just do it like this)

```
<FloatingPortal
                id="yoo-custom-toolbar-action-menu-list-portal"
                root={document.getElementById("yoopta-editor")}
              >
                <div
                  style={actionMenuStyles}
                  ref={actionMenuRefs.setFloating}
                  onClick={(e) => e.stopPropagation()}
                  className="dark:text-black"
                >
                  <ActionMenu {...actionMenuRenderProps} />
                </div>
              </FloatingPortal>
            )}
```

**Comment by trancethehuman** [comment]
But not sure how to resolve the side plus button and drag handle's colors

<img width="416" alt="image" src="https://github.com/user-attachments/assets/7041f197-6c58-40d4-9bb9-319533bf4025">

**Comment by trancethehuman** [comment]
Managed to fix these by overriding the css for stuff. I use tailwind and a global.css.

```css
#main-editor .yoopta-block-actions-plus,
#main-editor .yoopta-block-actions-drag {
  color: silver;
}

#main-editor .yoopta-extended-block-actions,
#main-editor .yoopta-block-options-menu-content {
  background-color: hsl(var(--popover));
  color: hsl(var(--card-foreground));
  border: none;
}
```

I couldn't find the className that targets the default menu action, so I opted for the Notion example and tweaked it's scss there.

Hope this is useful

**Comment by trancethehuman** [comment]
<img width="874" alt="Screenshot 2024-09-13 at 4 29 55 PM" src="https://github.com/user-attachments/assets/d52be38d-8c88-433a-8c50-246bc0c13bef">

Still have issues in the code menu and stuff too though - not sure how to fix these

**Comment by Darginec05** [comment]
I'll add some common readable classnames (not tailwind classes) to these components.
So this should make it easy to manage styles for any theme.

FYI @iamhenry @debkanchan @trancethehuman

**Comment by trancethehuman** [comment]
Sounds great!

**Comment by iamhenry** [comment]
thank you

**Comment by debkanchan** [comment]
Arigato

**Comment by Darginec05** [comment]
Merci

**Comment by debkanchan** [comment]
looks like it's fixed right? @Darginec05

**Comment by Darginec05** [comment]
@debkanchan Yes, it's actually fixed in the latest release, but I'm working on updating the examples to clearly show how it works with dark themes

**Comment by trancethehuman** [comment]
<img width="1062" alt="Screenshot 2024-09-24 at 2 59 21 PM" src="https://github.com/user-attachments/assets/474e8e7e-294f-4b84-8bdf-d1bddedde5a8">

<img width="785" alt="Screenshot 2024-09-24 at 3 00 18 PM" src="https://github.com/user-attachments/assets/3f4cef36-19ef-4a6d-9ba6-3358680bcb0c">


Still getting white out text on toolbars and such - also looked in the sandbox docs but couldn't find a classname to target these

**Comment by Darginec05** [comment]
@trancethehuman To style Toolbar I suggest to use these classnames - https://github.com/Darginec05/Yoopta-Editor/blob/master/web/next-example/src/styles/globals.scss#L71

And it works in examples with dark theme - https://yoopta.dev/examples/withDarkTheme

Let me know if it helps you.

**Comment by trancethehuman** [comment]
.yoopta-toolbar-root works!

I still have issues with the menu for codeblock languages.

Also, how do I change the background color for the buttons in the default toolbar? When in darkmode, the hover bg is quite bright

<img width="529" alt="image" src="https://github.com/user-attachments/assets/e117fc68-7043-4577-951c-ea3515073840">


<img width="598" alt="Screenshot 2024-09-24 at 3 30 36 PM" src="https://github.com/user-attachments/assets/e040c86d-70de-49a6-a932-4fb5e3dde739">

**Comment by Darginec05** [comment]
Related to https://github.com/Darginec05/Yoopta-Editor/issues/277

**Comment by Darginec05** [comment]
@trancethehuman I'm working on related task.
It will be fixed in the next patch release

But for now you can use this hack: 

```css
[data-radix-popper-content-wrapper] button {
    color: #000;
}
```

**Comment by trancethehuman** [comment]
Thanks! Fixed my codeblock language panel

**Comment by Quietscher** [comment]
The dark Mode dies Not work for me. Im using Nextjs with shadcn

**Comment by Quietscher** [comment]
I am using the useTheme(); handle but it does not change the popover with the marker options

**Comment by Quietscher** [comment]
![image](https://github.com/user-attachments/assets/e86ecb95-9538-470e-bc71-9b8dea8850ad)

**Comment by whitetown** [comment]
Unfortunately, there are a lot of hardcoded colors.
I have solved it like the css below, but it would be nice to use semantic colors everywhere.


```

.dark,
[data-theme='dark'] {
    .yoopta-toolbar-root {
        background-color: var(--color-base-100) !important;
        border-color: color-mix(in oklab, var(--color-base-content) 30%, transparent) !important;
    }

    .yoopta-toolbar-separator {
        background-color: color-mix(in oklab, var(--color-base-content) 30%, transparent) !important;
    }

    .yoopta-toolbar-item:hover,
    .yoopta-toolbar-item-mark:hover {
        background-color: var(--color-base-300) !important;
    }

    .yoopta-mark-code {
        background-color: var(--color-base-300) !important;
    }

    .yoopta-extended-block-actions {
        background-color: var(--color-base-100) !important;
    }

    .yoopta-block-options-menu-content {
        background-color: var(--color-base-100) !important;
        border-color: color-mix(in oklab, var(--color-base-content) 30%, transparent) !important;
    }

    .yoopta-block-options-button:hover {
        background-color: var(--color-base-300) !important;
    }

    .yoo-code-text-popover-foreground {
        background-color: var(--color-base-200) !important;
    }

    .yoo-code-text-popover-foreground > * > .yoopta-button:hover {
        background-color: var(--color-base-300) !important;
    }

    .yoopta-action-menu-list-content {
        background-color: var(--color-base-100) !important;
        border-color: color-mix(in oklab, var(--color-base-content) 30%, transparent) !important;
    }

    .yoopta-action-menu-list-content > * > * > .yoopta-button:hover {
        background-color: var(--color-base-300) !important;
    }

    .yoopta-action-menu-list-content > * > * > .yoopta-button[aria-selected='true'] {
        background-color: var(--color-base-300) !important;
    }

    .yoopta-action-menu-list-content > * > * > .yoopta-button > .yoo-action-menu-flex {
        background-color: var(--color-base-200) !important;
    }

    .yoopta-block-actions-plus,
    .yoopta-block-actions-drag {
        color: color-mix(in oklab, var(--color-base-content) 30%, transparent) !important;
    }

    .yoopta-block-actions-plus:hover,
    .yoopta-block-actions-drag:hover {
        color: color-mix(in oklab, var(--color-base-content) 60%, transparent) !important;
    }

    .yoopta-link-preview {
        background-color: var(--color-base-100) !important;
        border-color: color-mix(in oklab, var(--color-base-content) 30%, transparent) !important;
    }
}
```

One more small detail: in the file DefaultToolbarRender.tsx:
```
const getModalTriggerStyle = (modal: keyof ModalsState) => ({
        backgroundColor: isActiveTriggerModal(modal) ? 'var(--color-base-300)' : undefined,
    })
```

- --color-base-100
- --color-base-200
- --color-base-300
- --color-base-content
 are names from [daisyui](https://daisyui.com/) which I use in my project.


Also, it's not related to the issue, but I would suggest to use semantic colors in ColorPicker too.
```
const COLOR_PRESETS = {
    text: [
        { name: 'Default', value: 'var(--color-base-content)' },
        { name: 'Base-Content-100', value: 'var(--color-base-content-100)' },
        { name: 'Base-Content-200', value: 'var(--color-base-content-200)' },
        { name: 'Base-Content-300', value: 'var(--color-base-content-300)' },
        { name: 'Primary', value: 'var(--color-primary)' },
        { name: 'Secondary', value: 'var(--color-secondary)' },
        { name: 'Success', value: 'var(--color-success)' },
        { name: 'Warning', value: 'var(--color-warning)' },
        { name: 'Info', value: 'var(--color-info)' },
        { name: 'Danger', value: 'var(--color-error)' },
    ],
    background: [
        { name: 'Default', value: 'unset' },
        { name: 'Base-100', value: 'var(--color-base-100)' },
        { name: 'Base-200', value: 'var(--color-base-200)' },
        { name: 'Base-300', value: 'var(--color-base-300)' },
        { name: 'Primary', value: 'var(--color-primary)' },
        { name: 'Secondary', value: 'var(--color-secondary)' },
        { name: 'Success', value: 'var(--color-success)' },
        { name: 'Warning', value: 'var(--color-warning)' },
        { name: 'Info', value: 'var(--color-info)' },
        { name: 'Danger', value: 'var(--color-error)' },
    ],
}

```

it makes correct text-color/background-color regardless of light/dark mode.

Otherwise I am falling in love with the editor ;-)
